addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.7")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.10.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.6.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.4.4")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"              % "sbt-scalajs" % "1.20.2")
addSbtPlugin("org.scala-native"          % "sbt-scala-native" % "0.5.10")
