addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.11.2")
addSbtPlugin("com.github.sbt"            % "sbt-header"     % "5.11.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.6.4")
addSbtPlugin("org.typelevel"             % "sbt-tpolecat"   % "0.5.4")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"              % "sbt-scalajs" % "1.21.0")
addSbtPlugin("org.scala-native"          % "sbt-scala-native" % "0.5.11")
