addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.7")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.6.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.5.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.17")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs" % "1.13.0")
addSbtPlugin("org.scala-native"          % "sbt-scala-native" % "0.4.12")
